[
    { name: "Ouagadougou", count: 127 },
    { name: "Bobo Dioulasso", count: 10 },
    { name: "Banfora", count: 1 },
    { name: "Arbinda", count: 0 },
    { name: "Bagré", count: 0 },
    { name: "Batié", count: 0 },
    { name: "Bogandé", count: 0 },
    { name: "Boulsa", count: 0 },
    { name: "Boromo", count: 6 },
    { name: "Boussé", count: 0 },
    { name: "Dano", count: 0 },
    { name: "Dédougou", count: 2 },
    { name: "Diapaga", count: 0 },
    { name: "Diébougou", count: 0 },
    { name: "Djibo", count: 0 },
    { name: "Dori", count: 0 },
    { name: "Fada N'gourma", count: 0 },
    { name: "Gaoua", count: 0 },
    { name: "Garango", count: 0 },
    { name: "Gayéri", count: 0 },
    { name: "Gorom-Gorom", count: 0 },
    { name: "Gourcy", count: 0 },
    { name: "Houndé", count: 3 },
    { name: "Kantchari", count: 0 },
    { name: "Kaya", count: 0 },
    { name: "Kindi", count: 0 },
    { name: "Kokologo", count: 0 },
    { name: "Kombissiri", count: 0 },
    { name: "Kcountgoussi", count: 0 },
    { name: "Kordié", count: 0 },
    { name: "Koudougou", count: 0 },
    { name: "Kouka, Bam", count: 0 },
    { name: "Kouka, Banwa", count: 0 },
    { name: "Koupéla", count: 0 },
    { name: "Léo", count: 0 },
    { name: "Loropeni", count: 0 },
    { name: "Manga", count: 1 },
    { name: "Méguet", count: 0 },
    { name: "Mogtedo", count: 0 },
    { name: "Niangoloko", count: 0 },
    { name: "Nouna", count: 0 },
    { name: "Orodara", count: 0 },
    { name: "Ouahigouya", count: 0 },
    { name: "Ouargaye", count: 0 },
    { name: "Pama", count: 0 },
    { name: "Pissila", count: 0 },
    { name: "Pô", count: 0 },
    { name: "Pouytenga", count: 0 },
    { name: "Réo", count: 0 },
    { name: "Sapcounté", count: 0 },
    { name: "Sapouy", count: 0 },
    { name: "Sebba", count: 0 },
    { name: "Séguénéga", count: 0 },
    { name: "Sindou", count: 0 },
    { name: "Solenzo", count: 0 },
    { name: "Tangin Dassouri", count: 0 },
    { name: "Tenkodogo", count: 0 },
    { name: "Tikaré", count: 0 },
    { name: "Titao", count: 0 },
    { name: "Toma", count: 0 },
    { name: "Tougan", count: 0 },
    { name: "Villy", count: 0 },
    { name: "Yako", count: 0 },
    { name: "Ziniaré", count: 0 },
    { name: "Zorgo", count: 0 }
];